version: 2

models:
  - name: dim_crashes
    description: Crashes occurred and it's details.
    columns:
      - name: crash_record_id
        description: This number can be used to link to the same crash in the dim_vehicles and dim_people tables. 
                     This number also serves as a unique ID in this table.
        data_tests:
          - unique
          - not_null

      - name: crash_date
        description: Date and time of crash.


  - name: dim_fatalities
    description: Fatalities occurred during the crashes.
    columns:
      - name: person_id
        description: Unique ID linking this record to the dim_person table.
        data_tests:
          - unique
          - not_null

      - name: crash_location
        description: Estimated address of crash based on crash report.


      - name: crash_date
        description: crash occurring date.

  - name: dim_peoples
    description: Peoples injured/ died in crashes.
    columns:
      - name: person_id
        description: A unique identifier for each person record. IDs starting with P indicate passengers.
                     IDs starting with O indicate a person who was not a passenger in the vehicle 
                     (e.g., driver, pedestrian, cyclist, etc.).
        data_tests:
          - not_null
          - unique

      - name: person_type
        description: Type of roadway user involved in crash
      - name: vehicle_id
        description: The corresponding CRASH_UNIT_ID from the dim_vehicles table.


      - name: crash_record_id
        description: This number can be used to link to the same crash in the dim_crashes and dim_vehicles datasets.
                    This number also serves as a unique ID in the Crashes dataset.



  - name: dim_vehicles
    description: Vehicles involved in crashes.
    columns:
      - name: crash_unit_id
        description: A unique identifier for each vehicle record(Primary_key).
        data_tests:
          - not_null
          - unique

      - name: crash_record_id
        description: This number can be used to link to the same crash in the dim_crashes and dim_peoples.
        data_tests:
          - not_null



